from llm import ask_llm
from prompts import EXECUTOR_PROMPT


def execute_tasks(tasks, user_request):
    """
    Executes every task generated by the planner and
    combines all outputs into a single document.
    """

    completed_tasks = []
    document_sections = []

    for task in tasks:

        print(f"[Executor] Executing: {task['task']}")

        prompt = EXECUTOR_PROMPT.replace(
            "{request}", user_request
        ).replace(
            "{task}", task["task"]
        )

        try:
            result = ask_llm(prompt)

        except Exception as e:
            result = f"Task execution failed: {e}"

        completed_task = {
            "id": task["id"],
            "task": task["task"],
            "status": "completed",
            "result": result
        }

        completed_tasks.append(completed_task)

        document_sections.append(
            f"# {task['task']}\n\n{result}"
        )

    full_document = "\n\n".join(document_sections)

    return {
        "tasks": completed_tasks,
        "document": full_document
    }